// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoDemoService2.proto

package com.ominext.grpc.demo;

public final class ProtoDemoService2 {
  private ProtoDemoService2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Feature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Feature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Rectangle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Rectangle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RouteSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RouteSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RouteNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RouteNote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ProtoDemoService2.proto\",\n\005Point\022\020\n\010la" +
      "titude\030\001 \001(\005\022\021\n\tlongitude\030\002 \001(\005\".\n\007Featu" +
      "re\022\020\n\010latitude\030\001 \001(\005\022\021\n\tlongitude\030\002 \001(\005\"" +
      "0\n\tRectangle\022\020\n\010latitude\030\001 \001(\005\022\021\n\tlongit" +
      "ude\030\002 \001(\005\"3\n\014RouteSummary\022\020\n\010latitude\030\001 " +
      "\001(\005\022\021\n\tlongitude\030\002 \001(\005\"0\n\tRouteNote\022\020\n\010l" +
      "atitude\030\001 \001(\005\022\021\n\tlongitude\030\002 \001(\0052\245\001\n\nRou" +
      "teGuide\022\036\n\nGetFeature\022\006.Point\032\010.Feature\022" +
      "&\n\014ListFeatures\022\n.Rectangle\032\010.Feature0\001\022" +
      "&\n\013RecordRoute\022\006.Point\032\r.RouteSummary(\001\022",
      "\'\n\tRouteChat\022\n.RouteNote\032\n.RouteNote(\0010\001" +
      "B\031\n\025com.ominext.grpc.demoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Point_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_Feature_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Feature_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_Rectangle_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Rectangle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Rectangle_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_RouteSummary_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RouteSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RouteSummary_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_RouteNote_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RouteNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RouteNote_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
